// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFiStB6jgHeP7g6G6ryCbXABwtAkxSRj8',
    appId: '1:966421888594:web:61bd27af90252eec8fe98b',
    messagingSenderId: '966421888594',
    projectId: 'amaze-cart-66746',
    authDomain: 'amaze-cart-66746.firebaseapp.com',
    storageBucket: 'amaze-cart-66746.appspot.com',
    measurementId: 'G-G295P3SM8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWkwmu5TPMXoBFi9MbzH1rG2KcvxgxcQo',
    appId: '1:966421888594:android:8a842eb22ac84a4f8fe98b',
    messagingSenderId: '966421888594',
    projectId: 'amaze-cart-66746',
    storageBucket: 'amaze-cart-66746.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ1cQq0C2CD5jVutIuUq58eIaN_oSZRuo',
    appId: '1:966421888594:ios:9c2cc613ad85ce088fe98b',
    messagingSenderId: '966421888594',
    projectId: 'amaze-cart-66746',
    storageBucket: 'amaze-cart-66746.appspot.com',
    iosBundleId: 'com.amazecart.mainapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ1cQq0C2CD5jVutIuUq58eIaN_oSZRuo',
    appId: '1:966421888594:ios:9c2cc613ad85ce088fe98b',
    messagingSenderId: '966421888594',
    projectId: 'amaze-cart-66746',
    storageBucket: 'amaze-cart-66746.appspot.com',
    iosBundleId: 'com.amazecart.mainapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFiStB6jgHeP7g6G6ryCbXABwtAkxSRj8',
    appId: '1:966421888594:web:18c08d0fa759d10f8fe98b',
    messagingSenderId: '966421888594',
    projectId: 'amaze-cart-66746',
    authDomain: 'amaze-cart-66746.firebaseapp.com',
    storageBucket: 'amaze-cart-66746.appspot.com',
    measurementId: 'G-NGBKKNVZF0',
  );
}
